### ISSUE TITLE
GeoIP Token?

### ISSUE THREAD

**Issue by x86txt** [Gowee/traceroute-map-panel#2]
How/where do we input the GeoIP token for IPinfo?

**Comment by wasabi222** [comment]
I just upgraded from grafana 5 to grafana 7 and this option is now missing in grafana 7 - it was formerly located on the side panel in grafana 5

**Comment by Gowee** [comment]
Sorry for the late reply. It appears that I mistakenly turned off all notifications from the repo, some day.


The API token of IPInfo can be obtained by signing up on their websites: https://ipinfo.io/signup. 

To specify the token, assuming it is on Grafana 7.0:
1. "__Edit__" the panel:
![image](https://user-images.githubusercontent.com/8171899/98635965-d8704100-2360-11eb-8ac6-29977c77d9f2.png)
2. Options are merged into the section of panel settings on Grafana 7.0. Just scroll down and there are. 
![image](https://user-images.githubusercontent.com/8171899/98636037-03f32b80-2361-11eb-8841-f74b5ae330cb.png)


BTW, as Grafana breaks plugin compatibility between their major version, please make sure correspondinig version is installed: [v0.1.0](https://github.com/Gowee/traceroute-map-panel/releases/tag/v0.1.0) is for Grafana 6.7.x and [recent releases](https://github.com/Gowee/traceroute-map-panel/releases/tag/v0.2.3) are for Grafana 7.0+. The panel has not been tested on Grafana 5. But if it does not show errors just after installing, then it should work (no guarantee).

Feel free to left messages again if you still find it confusing.

**Comment by Gowee** [comment]
I am closing this issue for now as it has not received new comments for a few days. Please re-open it if necessary.

**Comment by Gowee** [comment]
Hi there!

It is a late update. I found that some a version between Grafana 7.1 - 7.3 dropped the support of an internal API used by the plugin silently without raising an error (#5), which may result in missing option editor.

I did not notice this issue until issue #4 is raised as I was using an outdated version of Grafana for months. Since then, I have rewritten the panel plugin to be compatible with the new APIs of the Grafana 7.x series. The new beta version is [here](https://github.com/Gowee/traceroute-map-panel/releases/tag/v0.3.0-beta1). It should work well with the latest Grafana.

Since the new version has not yet been included in the official plugin repo of Grafana, installation requires manual operation and does not support the Grafana cloud. If everything goes well, I will make a stable release and update it in the plugin repo next week. 
 
I feel sorry for the confusion.
