### ISSUE TITLE
Unable to see GeoIP options in Grafana 7.4

### ISSUE THREAD

**Issue by dodgeboy** [Gowee/traceroute-map-panel#4]
The panel tab in Grafana does not show the GeoIP provider/token options in Grafana 7.4.  Is this plugin compatible with this version of Grafana?  I was sure to download the latest zip and install from that.

**Comment by Gowee** [comment]
Hi, dodgeboy.

Thanks for your report. Actually, the plugin has not got a chance to test on Grafana 7.4 yet.

I confirmed the problem with my installation and am looking into this issue. Because I am celebrating the Spring Festival with family, the fix might take a long time.

Anyway, at a first glance, it appears to be due to some breaking changes of UI components introduced by Grafana.

**Comment by dodgeboy** [comment]
Thank you for your response!  I look forward to the fix when you have time.  Enjoy your holiday!

**Comment by Gowee** [comment]
Hello, dodgeboy.

[A new beta release](https://github.com/Gowee/traceroute-map-panel/releases/tag/v0.3.0-beta1) is here. Besides fixing this issue, it also comes with a bunch of new features, which take a longer time than expected to implement. 

Since the new version has not yet been included in the official plugin repo of Grafana, installation requires manual operation and does not support the Grafana cloud. If everything goes well, I will make a stable release and update it in the plugin repo next week.

Suggestions and feedback would be greatly appreciated.

**Comment by dodgeboy** [comment]
I am now able to configure GeoIP, and see the visual traceroute information on the map.  Thanks for fixing this!

**Comment by dodgeboy** [comment]
I noticed that changing the Bogon filtering space option doesn't seem to save.  If i set it to none, it reverts back to "Bogon (private + reserved)" next time I enter the settings menu.

**Comment by Gowee** [comment]
My oversight. It should be fixed by https://github.com/Gowee/traceroute-map-panel/commit/5e98274c45a2dbc38478677fe31db62fa908113d, which will be included in a later release.

Thanks again!
