### ISSUE TITLE
Error -Invalid Schema

### ISSUE THREAD

**Issue by neelanjan-msf** [Gowee/traceroute-map-panel#9]
Hi, I am using Grafana 7.3.6 with InfluxDB.

Objective is to track gps device, where gps device is storing latitude and longitude data in to the influxdb in float format.

Query :SELECT last("Lat") as latitude, last("Long") as longitude FROM "DishaLite" WHERE ${__to}ms - 5m <= time AND time <= ${__to}ms group by IMEI

I am getting Invalid Schema: Error
Please help

**Comment by Gowee** [comment]
Hi, neelanjan-msf.

The panel is meant for visualizing [traceroute](https://en.wikipedia.org/wiki/Traceroute), which is a "computer network diagnostic command for displaying possible routes (paths) and measuring transit delays of packets across an Internet Protocol (IP) network." Hence the panel expects IP addresses, instead of lat-lngs, as input. 

For general-purpose GPS location tracking, https://grafana.com/grafana/plugins/?search=map lists some other panel plugins.

I realize the name "traceroute" might be a little confusing. I will update the README to mention that.

**Comment by Gowee** [comment]
Thanks for the issue anyway.

I am closing it. Feel free to reply or open a new issue if you have other suggestions or problems on the plugin.
